# Logic-Ferret package

from .schema_contract import (
    SCHEMA_VERSION,
    SENSOR_REGISTRY,
    LAYER_NAMES,
    SIGNAL_LEVELS,
    FALLACY_NAMES,
    SIGNATURES,
    SignatureMismatch,
    assert_signatures,
    DIAGNOSE,
    ANNOTATE_TEXT,
    CALCULATE_C3,
    DISCOURSE_COLLAPSE_DETECT,
    GREEN,
    AMBER,
    RED,
    BLACK,
    TIER_LEVELS,
    SIGNAL_TO_TIER,
    CAMOUFLAGE_TIER_THRESHOLDS,
    DISCOURSE_COLLAPSE_MODES,
    ELEVATION_CLAUSES,
    REPORTAGE_DEESCALATED_SUFFIX,
    score_to_tier,
    layer_tiers,
    sensor_tiers,
    ferret_surface,
)

from .knowledge.study_scope_audit import (
    Coupling,
    Regime,
    ScopeStatus,
    InstrumentAudit,
    ProtocolAudit,
    DomainCouplingAudit,
    RegimeAudit,
    CausalModelAudit,
    ScopeBoundary,
    StudyScopeAudit,
    PREMISE,
    AI_REASONING_RULE,
    META_INSIGHT,
    HISTORICAL_CASES,
)

from .knowledge.informational_cost_audit import (
    GEOCENTRIC_COMFORT_STATE,
    ANOMALIES_UNDER_GEOCENTRISM,
    INFORMATION_COST_ACCUMULATION,
    HELIOCENTRIC_UNCERTAINTY_STATE,
    INFORMATION_COST_AUDIT,
    INFORMATION_THEORY_INSIGHT,
    AI_IMPLICATIONS,
    HISTORICAL_PATTERN,
    VERDICT as INFORMATIONAL_COST_VERDICT,
)

__all__ = [
    # --- schema_contract (text-analysis surface) ---
    "SCHEMA_VERSION",
    "SENSOR_REGISTRY",
    "LAYER_NAMES",
    "SIGNAL_LEVELS",
    "FALLACY_NAMES",
    "SIGNATURES",
    "SignatureMismatch",
    "assert_signatures",
    "DIAGNOSE",
    "ANNOTATE_TEXT",
    "CALCULATE_C3",
    "DISCOURSE_COLLAPSE_DETECT",
    "GREEN",
    "AMBER",
    "RED",
    "BLACK",
    "TIER_LEVELS",
    "SIGNAL_TO_TIER",
    "CAMOUFLAGE_TIER_THRESHOLDS",
    "DISCOURSE_COLLAPSE_MODES",
    "ELEVATION_CLAUSES",
    "REPORTAGE_DEESCALATED_SUFFIX",
    "score_to_tier",
    "layer_tiers",
    "sensor_tiers",
    "ferret_surface",
    # --- study_scope_audit (AI-reasoning discipline) ---
    "Coupling",
    "Regime",
    "ScopeStatus",
    "InstrumentAudit",
    "ProtocolAudit",
    "DomainCouplingAudit",
    "RegimeAudit",
    "CausalModelAudit",
    "ScopeBoundary",
    "StudyScopeAudit",
    "PREMISE",
    "AI_REASONING_RULE",
    "META_INSIGHT",
    "HISTORICAL_CASES",
    # --- informational_cost_audit (reasoning artifact) ---
    # VERDICT is re-exported as INFORMATIONAL_COST_VERDICT to
    # avoid a generic name at package scope.
    "GEOCENTRIC_COMFORT_STATE",
    "ANOMALIES_UNDER_GEOCENTRISM",
    "INFORMATION_COST_ACCUMULATION",
    "HELIOCENTRIC_UNCERTAINTY_STATE",
    "INFORMATION_COST_AUDIT",
    "INFORMATION_THEORY_INSIGHT",
    "AI_IMPLICATIONS",
    "HISTORICAL_PATTERN",
    "INFORMATIONAL_COST_VERDICT",
]

